---
title: "Lab07"
author: "Tiago Perroni - 281972"
format: pdf
editor: visual
---

```{r setup, include=FALSE}
library(RSQLite)
library(dplyr)
```

```{r}
path <- "\\\\smb/ra281972/Downloads/ME315"
fname <- file.path(path, "database.sqlite3")

conn <- dbConnect(RSQLite::SQLite(), fname)
```

```{r}
query_gpa_professores <- "
  SELECT 
    i.name AS professor,
    SUM(gd.a_count * 4.0 + 
        gd.ab_count * 3.5 + 
        gd.b_count * 3.0 + 
        gd.bc_count * 2.5 + 
        gd.c_count * 2.0 + 
        gd.d_count * 1.0 + 
        gd.f_count * 0.0) * 1.0 / 
    SUM(gd.a_count + gd.ab_count + gd.b_count + gd.bc_count + gd.c_count +
    gd.d_count + gd.f_count) AS gpa_medio,
    SUM(gd.a_count + gd.ab_count + gd.b_count + gd.bc_count + gd.c_count +
    gd.d_count + gd.f_count) AS total_alunos
  FROM instructors i
  INNER JOIN teachings t ON i.id = t.instructor_id
  INNER JOIN sections sec ON t.section_uuid = sec.uuid
  INNER JOIN course_offerings co ON sec.course_offering_uuid = co.uuid
  INNER JOIN grade_distributions gd ON co.uuid = gd.course_offering_uuid
  INNER JOIN subject_memberships sm ON co.uuid = sm.course_offering_uuid
  INNER JOIN subjects s ON sm.subject_code = s.code
  WHERE s.abbreviation = 'STAT'
  GROUP BY i.id, i.name
  HAVING total_alunos > 0;
"

professores_gpa <- dbGetQuery(conn, query_gpa_professores)

prof_mais_dificil <- professores_gpa %>% arrange(gpa_medio) %>% slice(1)

prof_mais_facil <- professores_gpa %>% arrange(desc(gpa_medio)) %>% slice(1)

cat("Professor Mais Difícil:\n")
print(prof_mais_dificil)

cat("\nProfessor Mais Fácil:\n")
print(prof_mais_facil)
```

```{r}
query_gpa_disciplinas <- "
  SELECT 
    c.name AS nome_disciplina,
    c.number AS numero_disciplina,
    SUM(gd.a_count * 4.0 + 
        gd.ab_count * 3.5 + 
        gd.b_count * 3.0 + 
        gd.bc_count * 2.5 + 
        gd.c_count * 2.0 + 
        gd.d_count * 1.0 + 
        gd.f_count * 0.0) * 1.0 / 
    SUM(gd.a_count + gd.ab_count + gd.b_count + gd.bc_count + gd.c_count +
    gd.d_count + gd.f_count) AS gpa_medio,
    SUM(gd.a_count + gd.ab_count + gd.b_count + gd.bc_count + gd.c_count +
    gd.d_count + gd.f_count) AS total_alunos
  FROM courses c
  INNER JOIN course_offerings co ON c.uuid = co.course_uuid
  INNER JOIN grade_distributions gd ON co.uuid = gd.course_offering_uuid
  INNER JOIN subject_memberships sm ON co.uuid = sm.course_offering_uuid
  INNER JOIN subjects s ON sm.subject_code = s.code
  WHERE s.abbreviation = 'STAT'
  GROUP BY c.uuid, c.name, c.number
  HAVING total_alunos > 0;
"

disciplinas_gpa <- dbGetQuery(conn, query_gpa_disciplinas)

disc_mais_dificil <- disciplinas_gpa %>% arrange(gpa_medio) %>% slice(1)

disc_mais_facil <- disciplinas_gpa %>% arrange(desc(gpa_medio)) %>% slice(1)

cat("Disciplina Mais Difícil:\n")
print(disc_mais_dificil)

cat("\nDisciplina Mais Fácil:\n")
print(disc_mais_facil)
```

```{r}
dbDisconnect(conn)
```