---
title: "Lab06"
author: "Tiago Perroni - 281972"
format: pdf
editor: visual
---

```{r}
library(RSQLite)
library(dplyr)
```

```{r}
path <- "\\\\smb/ra281972/Downloads/ME315"
fname <- file.path(path, "disco.db")
```

```{r}
conn <- dbConnect(RSQLite::SQLite(), fname)
```

```{r}
tabelas <- dbListTables(conn)
tabelas
```

```{r}
colunas_customers <- dbListFields(conn, "customers")
colunas_customers
```

```{sql connection=conn}
SELECT COUNT(*) AS total_clientes FROM customers
```
```{sql connection=conn}
SELECT COUNT(DISTINCT Country) AS total_paises FROM customers
```
```{sql connection=conn}
SELECT Country, COUNT(*) AS quantidade FROM customers
GROUP BY Country
ORDER BY quantidade DESC
```
```{sql connection=conn}
SELECT Country, COUNT(*) AS quantidade FROM customers
GROUP BY Country
ORDER BY quantidade DESC
LIMIT 5
```
```{sql connection=conn}
SELECT DISTINCT Country FROM customers
WHERE Country GLOB '??????';
```

```{sql connection=conn}
SELECT DISTINCT t.Name AS Nome_Musica FROM customers c
INNER JOIN invoices i ON c.CustomerId = i.CustomerId
INNER JOIN invoice_items ii ON i.InvoiceId = ii.InvoiceId
INNER JOIN tracks t ON ii.TrackId = t.TrackId
WHERE c.Country = 'Brazil';
```

```{r parte-11}
dbDisconnect(conn)
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```

