---
title: "Lista02"
author: "Tiago Perroni"
format: pdf
editor: visual
---

# Conexao R -\> SQL

```{r}
library(DBI)
library(RSQLite)
# Conexao com SQL
con <- dbConnect(SQLite(), "me315.sqlite")
```

## Hands-On

1.  

```{sql connection=con}
SELECT * FROM PRESERVE
ORDER BY "ACRES"
```

2.  

```{sql connection=con}
SELECT PNAME, FEE FROM PRESERVE
WHERE STATE == "MT"
ORDER BY PNAME DESC
```

3.  

```{sql connection=con}
SELECT FEE, ACRES FROM PRESERVE
ORDER BY FEE, ACRES
```

4.  

```{sql connection=con}
SELECT PNAME FROM PRESERVE
ORDER BY PNO
```

5.  

```{sql connection=con}
SELECT STATE, FEE, PNO FROM PRESERVE
WHERE ACRES > 100
ORDER BY STATE DESC, FEE DESC, PNO
```

6.  

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE STATE >= 'M'
```

7.  

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE PNAME < 'TATKON'
```

9.  

```{sql connection=con}
SELECT * FROM EMPLOYEE
ORDER BY ENAME
```

10. 

```{sql connection=con}
SELECT ENAME, SALARY FROM EMPLOYEE
WHERE SALARY > 2000
ORDER BY SALARY DESC
```

11. 

```{sql connection=con}
SELECT DNO, ENO, ENAME FROM EMPLOYEE
ORDER BY DNO DESC, ENO
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
